# packages in environment at /Users/dglandorf/opt/miniconda3/envs/LD-inference:
#
# Name                    Version                   Build  Channel
aiohttp                   3.8.3           py310h6c40b1e_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
anyio                     3.6.2                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2           py310hecd8cb5_0  
asynctest                 0.13.0                     py_0  
attrs                     22.2.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    5.0.1                    pypi_0    pypi
bottleneck                1.3.5           py310h4e76f89_0  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotli-python             1.0.9           py310he9d5cce_7  
brotlipy                  0.7.0           py310hca72f7f_1002  
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.01.10           hecd8cb5_0  
certifi                   2022.12.7       py310hecd8cb5_0  
cffi                      1.15.1          py310hc55c11b_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
chatgpt                   0.1.0                    pypi_0    pypi
click                     8.0.4           py310hecd8cb5_0  
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.2                    pypi_0    pypi
cryptography              38.0.1          py310hf6deb26_0  
cycler                    0.11.0             pyhd3eb1b0_0  
dash                      2.7.0           py310hecd8cb5_0  
dash-bootstrap-components 1.3.0                    pypi_0    pypi
dash-cytoscape            0.3.0                    pypi_0    pypi
debugpy                   1.6.5                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.6           py310hecd8cb5_0  
entrypoints               0.4                      pypi_0    pypi
et_xmlfile                1.1.0           py310hecd8cb5_0  
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
flask                     2.2.2           py310hecd8cb5_0  
flask-compress            1.13            py310hecd8cb5_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               hd8bbffd_0  
frozenlist                1.3.3           py310h6c40b1e_0  
giflib                    5.2.1                haf1e3a3_0  
greenlet                  2.0.1                    pypi_0    pypi
idna                      3.4             py310hecd8cb5_0  
intel-openmp              2021.4.0          hecd8cb5_3538  
ipykernel                 6.20.1                   pypi_0    pypi
ipython                   8.8.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.2                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.0.1              pyhd3eb1b0_0  
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2           py310hecd8cb5_0  
joblib                    1.1.1           py310hecd8cb5_0  
jpeg                      9e                   hca72f7f_0  
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-core              5.1.3                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.1.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.1                    pypi_0    pypi
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.2           py310he9d5cce_0  
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
levenshtein               0.20.9                   pypi_0    pypi
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.8                  h9ed2024_5  
libffi                    3.3                  hb1e8313_2  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libtiff                   4.4.0                h2ef1027_1  
libwebp                   1.2.4                h56c3ce4_0  
libwebp-base              1.2.4                hca72f7f_0  
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h23ab428_1  
markupsafe                2.1.1           py310hca72f7f_0  
matplotlib                3.5.3           py310hecd8cb5_0  
matplotlib-base           3.5.3           py310hfb0c5b7_0  
matplotlib-inline         0.1.6           py310hecd8cb5_0  
mistune                   2.0.4                    pypi_0    pypi
mkl                       2021.4.0           hecd8cb5_637  
mkl-service               2.4.0           py310hca72f7f_0  
mkl_fft                   1.3.1           py310hf879493_0  
mkl_random                1.2.2           py310hc081a56_0  
multidict                 6.0.2           py310hca72f7f_0  
multiprocess              0.70.14         py310hecd8cb5_0  
munkres                   1.1.4                      py_0  
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.7                    pypi_0    pypi
nbformat                  5.7.3                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_3  
nest-asyncio              1.5.6                    pypi_0    pypi
nltk                      3.7                pyhd3eb1b0_0  
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numexpr                   2.8.4           py310h9638375_0  
numpy                     1.23.4          py310h9638375_0  
numpy-base                1.23.4          py310ha98c3c9_0  
openpyxl                  3.0.10          py310hca72f7f_0  
openssl                   1.1.1s               hca72f7f_0  
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.1           py310h3ea8b11_0  
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0           py310hde71d04_1  
pip                       22.3.1                   pypi_0    pypi
platformdirs              2.6.2                    pypi_0    pypi
playwright                1.28.0                   pypi_0    pypi
plotly                    5.9.0           py310hecd8cb5_0  
prometheus-client         0.15.0                   pypi_0    pypi
prompt-toolkit            3.0.36                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyee                      9.0.4                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pymupdf                   1.21.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9           py310hecd8cb5_0  
pypdf2                    2.10.5          py310hecd8cb5_0  
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.8               hdfd78df_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-dotenv             0.21.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.4                    pypi_0    pypi
pytz                      2022.1          py310hecd8cb5_0  
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.0                   pypi_0    pypi
rapidfuzz                 2.13.7                   pypi_0    pypi
readline                  8.2                  hca72f7f_0  
regex                     2022.7.9        py310hca72f7f_0  
requests                  2.28.1          py310hecd8cb5_0  
revchatgpt                0.0.29                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.5.0          py310hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.3               h707629a_0  
stack-data                0.6.2                    pypi_0    pypi
tenacity                  8.0.1           py310hecd8cb5_1  
terminado                 0.17.1                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
tls-client                0.1.5                    pypi_0    pypi
tornado                   6.2             py310hca72f7f_0  
tqdm                      4.64.1          py310hecd8cb5_0  
traitlets                 5.8.1                    pypi_0    pypi
tueplots                  0.0.7                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022f                h04d1e81_0  
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.12         py310hecd8cb5_0  
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2           py310hecd8cb5_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.6.1                    pypi_0    pypi
wikipedia                 1.4.0                    pypi_0    pypi
wikipedia-api             0.5.4                    pypi_0    pypi
xz                        5.2.6                hca72f7f_0  
yarl                      1.8.1           py310hca72f7f_0  
zeromq                    4.3.4                h23ab428_0  
zlib                      1.2.13               h4dc903c_0  
zstd                      1.5.2                hcb37349_0  
